### ISSUE TITLE
Adding a cli argument to only connect to OPC and not rebuild the config?

### ISSUE THREAD

**Issue by C0ntroller** [Praktikum-PvAS/process-historian#17]
Atm the program is designed to connect to the TripleStore and renew the opcua_config.json on _every_ start. If the user made changes in the config they are overwritten.

This only does not happen because the TripleStore is missing for now so we do nothing in this step.

So if the user want to change anything (like change "poll" to "subscription" for certain items) and restart the program changes won't work. 

Should we add a cli flag to allow the user to skip the refetch of the config? Or do we even want to design it like it only renews the config if the flag is used (or no config file found)?

**Comment by OParczyk** [comment]
Three possibilties:
a: Always create a new opc ua config from triplestore on startup unless flag is set

b: When there is no (or a barebone?) opc ua config, create a new one from the triple store. Otherwise skip this step, unless a flag is set forcing the recreation

C: Either a or b, but don't touch the interval of a given node to poll if rest of this node is unchanged unless forced.
Even better if we could identify the thing rather than the node, because the nodeid and namespace number could change, while the thing this node monitors stays the same. If I understood that correctly this kind of identifiability is a key advantage of using something like MTPs.

Because we can't implement the config builder we might want to refer to this issue in comments in the stubs.

**Comment by C0ntroller** [comment]
While A+C would be the most preferable imo, we currently don't have any "identification" of any node because there is no TripleStore. So this would be a problem for future developers (to implement the "identification").

**Comment by C0ntroller** [comment]
Because in our current dev state C cannot be implemented anyway I would suggest implementing A.

**Comment by OParczyk** [comment]
yeah, but mentioning this issue in a comment at least to hint towards what _should_ be there, should other people take over next year.

**Comment by OParczyk** [comment]
closed by #37
