### ISSUE TITLE
Deadlock in... push thread (?)

### ISSUE THREAD

**Issue by OParczyk** [Praktikum-PvAS/process-historian#34]
Steps to reproduce: Start opc and optionally influx server. Start process historian. Wait a bit and send a keyboard interrupt.

**Comment by C0ntroller** [comment]
For documentation puporses: The bug was caused by the opcua library. When trying to unsubscribe while there is no connection to the server, the function will raise an Error but will *not* terminate any subscription threads. The `disconnect()` method meanwhile terminates these threads even without connection to the server.

Because of the raise in the unsubscription, the disconnect didn't happend.

The subscription zombie thread still is in background thats why there is no "full" termination.
